name: image-build

on:
  schedule:
    - cron:  '0 * * * *'
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: build
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_buildmain
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/386
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/docker-nginx-http3:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  
