name: import-deb

on:
  schedule:
  - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Import Latest nginx.deb
        run: |
          wget https://github.com/ononoki1/nginx-http3/releases/latest/download/nginx.deb -O ./nginx.deb && git add nginx.deb
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Import Latest nginx.deb" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
